### ISSUE TITLE
Manipulating WordPress object cache

### ISSUE THREAD

**Issue by szepeviktor** [pantheon-systems/wp-redis#247]
Redis cache has no authentication, anyone not related to a specific website logs in to the server as a plain linux user can manipulate Redis keys.

Is it possible to steal sessions or create WP admin user through Redis keys?

**Comment by danielbachhuber** [comment]
> Redis cache has no authentication, anyone not related to a specific website logs in to the server as a plain linux user can manipulate Redis keys.

Sure, I think this falls into the category of: server things you need to make sure you configure appropriately.

In theory, this applies to any object cache, not just Redis.

> Is it possible to steal sessions or create WP admin user through Redis keys?

Not to my knowledge, no. You may be able to overload the email address of an existing user with your own, and then trigger a password reset.

**Comment by szepeviktor** [comment]
> trigger a password reset.

Thank you for sharing that with me.

**Comment by CyberCr33p** [comment]
Hello. I am new to REDIS. I want to see if it's possible to use REDIS with ACLs ( https://redis.io/topics/acl ) for multiple wordpress installations in same REDIS instance. Is it possible with ACLs each wordpress to have access to add/remove only it's own keys and don't have access to other users keys?

**Comment by szepeviktor** [comment]
No, wp-redis has no authentication feature.
You may separate WordPress installations by prefixes or by Redis DB - without any restriction.

**Comment by CyberCr33p** [comment]
I know wp-redis has no authentication feature.

But maybe wp-redis developers can consider to add it if redis ACLs described here: https://redis.io/topics/acl support keys write/read "seperation".

In the above URL I read this:

"Allow and disallow certain keys:
~<pattern>: Add a pattern of keys that can be mentioned as part of commands. For instance ~* allows all the keys. The pattern is a glob-style pattern like the one of KEYS. It is possible to specify multiple patterns. * allkeys: Alias for ~*. * resetkeys: Flush the list of allowed keys patterns. For instance the ACL ~foo:* ~bar:* resetkeys ~objects:*, will result in the client only be able to access keys matching the pattern objects:*."

So if wp-redis supported "AUTH <username> <password>" instead of "AUTH <password>" and configure to store keys with a prefix then wouldn't it possible to use one REDIS server with multiple wordpress instasllations and don't have security issues?
