### ISSUE TITLE
object-cache.php uses flushAll, not flushDb

### ISSUE THREAD

**Issue by wetcoast** [pantheon-systems/wp-redis#258]
The use of `flushAll` in object-cache.php is catastrophic if you are using multiple databases in Redis. Not sure why `flushdb` isn't used here instead since database partitioning is built in. 

We have 14 separate databases in our Redis implementation with different apps/services using different dBs. Couldn't explain why dBs were seemingly randomly losing all cached data until we eventually tracked it down to the use of wp-redis's object-cache.php in our WordPress projects, each of which is using a separate dB in a single Redis deployment.

**Comment by danielbachhuber** [comment]
Hey @wetcoast,

Thanks for the report!

> The use of `flushAll` in object-cache.php is catastrophic if you are using multiple databases in Redis.

Yep, definitely.

> Not sure why `flushdb` isn't used here instead since database partitioning is built in.

<strikethrough>Do you know if database partitioning has always been built into Redis, or is it a more recent thing?</strikethrough>. Seems like it's [been around since 1.0.0](https://redis.io/commands/flushdb)

It looks like the `flushAll` call landed in the mega `initial commit`, so I'm not sure there's much we can derive from history:

https://github.com/pantheon-systems/wp-redis/commit/c8486576b0d55552570a678998a68e55a8ea1f56#diff-5a2b681f0d32956de83215ea32388177R420-R423

However, another popular Redis object cache uses `flushdb()`, so it's probably fine to switch to: https://github.com/tillkruss/redis-cache/blob/master/includes/object-cache.php#L821

Our tests pass with it too #259

> We have 14 separate databases in our Redis implementation with different apps/services using different dBs. Couldn't explain why dBs were seemingly randomly losing all cached data until we eventually tracked it down to the use of wp-redis's object-cache.php in our WordPress projects, each of which is using a separate dB in a single Redis deployment.

Sorry about that :( Must've been a painful bug.

---

I'm hesitant to tag a new release right now. You're welcome to apply the change however most convenient if you want an immediate fix, and I'll tag WP Redis v0.8.0 with the change on the first full week of January.

**Comment by danielbachhuber** [comment]
@wetcoast This is now released in v0.8.0. Thanks again for the report.
