### ISSUE TITLE
Caching objects in backend dashboard

### ISSUE THREAD

**Issue by dingman** [pantheon-systems/wp-redis#260]
I have installed Query Monitor to see what might be causing slower load times in my backend, while browsing around. It says Redis caching is not in use, even though I have this plugin installed.

Is there a way to configure the plugin to leverage Redis caching in the backend to help support faster load times?

**Comment by danielbachhuber** [comment]
Hi @dingman,

A few questions to help us track down the root cause:

1. Is this on a Pantheon-hosted site?
2. Can you share more details about how you've configured the plugin, including confirmation that you've followed the [first installation step](https://github.com/pantheon-systems/wp-redis#installation), symlinking the provided `object-cache.php` file to `wp-content/object-cache.php`?
3. Can you share a screenshot of the Query Monitor message you see?

> Is there a way to configure the plugin to leverage Redis caching in the backend to help support faster load times?

If the plugin is installed correctly, it will work interchangeably for the frontend and the backend.

**Comment by dingman** [comment]
Aha! That solved it ;) I had forgotten to symlink it to your plugin's copy of it, and now it works.

I have EFS connected to my main AMI so I can replicate this AMI and not have to worry about file integrity across AMIs. Enabling the Redis caching took it from 4-5s load time for every page in the backend (for Page Generation Time), down to under 1s

Beautiful, we can close this. Stellar work :)

**Comment by danielbachhuber** [comment]
> Aha! That solved it ;) I had forgotten to symlink it to your plugin's copy of it, and now it works.

Great :)

> I have EFS connected to my main AMI so I can replicate this AMI and not have to worry about file integrity across AMIs. Enabling the Redis caching took it from 4-5s load time for every page in the backend (for Page Generation Time), down to under 1s

Nice!
