### ISSUE TITLE
Support for cache groups

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/wp-redis#44]
Redis supports it. WP's cache API support it. This plugin should probably support it. ;)

**Comment by szepeviktor** [comment]
Maybe it is implemented: `@param string $group Where to group the cache contents`
https://github.com/pantheon-systems/wp-redis/blob/a8e52f0037fded00a6fea4f23a5a26b4ec196824/object-cache.php#L323

**Comment by danielbachhuber** [comment]
> Maybe it is implemented:

Cache groups aren't _fully_ implemented currently, because WP Redis concatenates the key and group together to make a cache key. As I [discovered in this support thread](https://wordpress.org/support/topic/redis-and-formidable-pro-not-working-together?replies=8#post-7845001), WordPress actually stores object cache data in an associative array, meaning the group is properly persisted.

I didn't realize Redis natively supported cache groups though. It would certainly be ideal to not use concatenated keys, and properly offer purging by group.
